[debug] [2025-07-16T17:20:34.079Z] ----------------------------------------------------------------------
[debug] [2025-07-16T17:20:34.081Z] Command:       /usr/local/bin/node /home/project/node_modules/.bin/firebase login
[debug] [2025-07-16T17:20:34.081Z] CLI Version:   14.10.1
[debug] [2025-07-16T17:20:34.082Z] Platform:      linux
[debug] [2025-07-16T17:20:34.082Z] Node Version:  v20.19.1
[debug] [2025-07-16T17:20:34.082Z] Time:          Wed Jul 16 2025 22:50:34 GMT+0530 (India Standard Time)
[debug] [2025-07-16T17:20:34.082Z] ----------------------------------------------------------------------
[debug] 
[debug] [2025-07-16T17:20:34.084Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] i  The Firebase CLI’s MCP server feature can optionally make use of Gemini in Firebase. Learn more about Gemini in Firebase and how it uses your data: https://firebase.google.com/docs/gemini-in-firebase#how-gemini-in-firebase-uses-your-data 
[debug] [2025-07-16T17:20:35.151Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2025-07-16T17:20:35.151Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2025-07-16T17:20:47.311Z] HookError: [Inquirer] Hook functions can only be called from within a prompt
    at new HookError (/home/project/node_modules/@inquirer/core/dist/commonjs/lib/errors.js:22:1)
    at getStore (/home/project/node_modules/@inquirer/core/dist/commonjs/lib/hook-engine.js:42:15)
    at Object.clearAll (/home/project/node_modules/@inquirer/core/dist/commonjs/lib/hook-engine.js:111:23)
    at eval (/home/project/node_modules/@inquirer/core/dist/commonjs/lib/create-prompt.js:139:50)
    at <anonymous> (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.96435430.js:31:29397)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2025-07-16T17:21:10.480Z] ----------------------------------------------------------------------
[debug] [2025-07-16T17:21:10.482Z] Command:       /usr/local/bin/node /home/project/node_modules/.bin/firebase init
[debug] [2025-07-16T17:21:10.482Z] CLI Version:   14.10.1
[debug] [2025-07-16T17:21:10.482Z] Platform:      linux
[debug] [2025-07-16T17:21:10.482Z] Node Version:  v20.19.1
[debug] [2025-07-16T17:21:10.482Z] Time:          Wed Jul 16 2025 22:51:10 GMT+0530 (India Standard Time)
[debug] [2025-07-16T17:21:10.482Z] ----------------------------------------------------------------------
[debug] 
[debug] [2025-07-16T17:21:10.498Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2025-07-16T17:21:11.358Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/home/project/node_modules/google-auth-library/build/src/auth/googleauth.js:287:15)
    at async GoogleAuth._GoogleAuth_determineClient (/home/project/node_modules/google-auth-library/build/src/auth/googleauth.js:834:32)
    at async GoogleAuth.getClient (/home/project/node_modules/google-auth-library/build/src/auth/googleauth.js:698:20)
    at async GoogleAuth.getAccessToken (/home/project/node_modules/google-auth-library/build/src/auth/googleauth.js:722:24)
    at async autoAuth (/home/project/node_modules/firebase-tools/lib/requireAuth.js:26:19)
    at async Object.requireAuth (/home/project/node_modules/firebase-tools/lib/requireAuth.js:81:20)
    at async eval (/home/project/node_modules/firebase-tools/lib/command.js:242:17)
[error] 
[error] Error: Failed to authenticate, have you run firebase login?
[debug] [2025-07-16T17:21:11.597Z] Error: Unknown status code 530
    at _0x3c20a8 (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.96435430.js:31:1001993)
    at _0x50f252._readHeaders (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.96435430.js:31:1008379)
    at _0x50f252.execute (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.96435430.js:31:1006351)
    at Socket.socketOnData (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.97a3df4f.js:3:6073)
    at Socket.emit (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.97a3df4f.js:30:11034)
    at Socket.emit (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.97a3df4f.js:29:5199)
    at addChunk (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.97a3df4f.js:230:3174)
    at readableAddChunkPushByteMode (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.97a3df4f.js:230:6158)
    at Readable.push (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.97a3df4f.js:230:6192)
    at _0x1024d8.onStreamRead [as onread] (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.97a3df4f.js:216:2625)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2025-07-16T17:21:32.994Z] ----------------------------------------------------------------------
[debug] [2025-07-16T17:21:32.996Z] Command:       /usr/local/bin/node /home/project/node_modules/.bin/firebase login
[debug] [2025-07-16T17:21:32.996Z] CLI Version:   14.10.1
[debug] [2025-07-16T17:21:32.997Z] Platform:      linux
[debug] [2025-07-16T17:21:32.997Z] Node Version:  v20.19.1
[debug] [2025-07-16T17:21:32.997Z] Time:          Wed Jul 16 2025 22:51:32 GMT+0530 (India Standard Time)
[debug] [2025-07-16T17:21:32.997Z] ----------------------------------------------------------------------
[debug] 
[info] i  The Firebase CLI’s MCP server feature can optionally make use of Gemini in Firebase. Learn more about Gemini in Firebase and how it uses your data: https://firebase.google.com/docs/gemini-in-firebase#how-gemini-in-firebase-uses-your-data 
[debug] [2025-07-16T17:21:38.546Z] HookError: [Inquirer] Hook functions can only be called from within a prompt
    at new HookError (/home/project/node_modules/@inquirer/core/dist/commonjs/lib/errors.js:22:1)
    at getStore (/home/project/node_modules/@inquirer/core/dist/commonjs/lib/hook-engine.js:42:15)
    at Object.clearAll (/home/project/node_modules/@inquirer/core/dist/commonjs/lib/hook-engine.js:111:23)
    at eval (/home/project/node_modules/@inquirer/core/dist/commonjs/lib/create-prompt.js:139:50)
    at <anonymous> (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.96435430.js:31:29397)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2025-07-16T17:21:45.860Z] ----------------------------------------------------------------------
[debug] [2025-07-16T17:21:45.862Z] Command:       /usr/local/bin/node /home/project/node_modules/.bin/firebase login
[debug] [2025-07-16T17:21:45.863Z] CLI Version:   14.10.1
[debug] [2025-07-16T17:21:45.863Z] Platform:      linux
[debug] [2025-07-16T17:21:45.863Z] Node Version:  v20.19.1
[debug] [2025-07-16T17:21:45.863Z] Time:          Wed Jul 16 2025 22:51:45 GMT+0530 (India Standard Time)
[debug] [2025-07-16T17:21:45.863Z] ----------------------------------------------------------------------
[debug] 
[info] i  The Firebase CLI’s MCP server feature can optionally make use of Gemini in Firebase. Learn more about Gemini in Firebase and how it uses your data: https://firebase.google.com/docs/gemini-in-firebase#how-gemini-in-firebase-uses-your-data 
